<?php
namespace app\models;
use Yii;
use yii\base\Model;
use yii\imagine\Image;

class ImageUpload extends Model
{
    public $imageFile;
    public function rules()
    {
        return [
            ['imageFile', 'file', 'skipOnEmpty' => false, 'extensions' => 'jpg, png, jpeg']
        ];
//        return parent::attributeLabels(); //TODO: change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'imageFile' => 'Rasm fayli'
        ];
        return parent::attributeLabels(); //TODO
    }

    /**
     * @param $size
     * @return array|bool
     */
    public function upload($size)
    {
        if ($this->validate()) {
            $path = Yii::getAlias('@uploads');
            $fileName = uniqid();
            $fileExt = $this->imageFile->extension;
            $full_name = $fileName.'.'.$fileExt;
            if($this->imageFile->saveAs($path. '/' .$full_name))
                $thumb = $this->Imagine($full_name,$size);
                return [
                    'original' => $full_name,
                    'thumb' => $thumb,
                ];
            }

        return false;
    }

    /**
     * @param $org_image
     * @param $size
     * @return string
     */
    public function Imagine($org_image,$size)
    {
        $path = Yii::getAlias('@uploads');
        $thumbName = 'thumb_' .  $org_image;

        if ($size == 'news'){

            Image::thumbnail($path . '/' . $org_image, 200,200)->save($path . '/' . $thumbName);
        }
        else if ($size == 'gallery'){
            Image::thumbnail($path . '/' . $org_image, 200,200)->save($path . '/' . $thumbName);
        }

        return $thumbName;
    }
}