<?php
namespace app\models;
use Yii;
use yii\base\Model;

class ImageUpload1 extends Model
{
    public $imageFile;
    public function rules()
    {
        return [
            ['imageFile', 'file', 'skipOnEmpty' => false, 'extensions' => 'jpg, png, jpeg']
        ];
//        return parent::attributeLabels(); //TODO: change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'imageFile' => 'Rasm fayli'
        ];
        return parent::attributeLabels(); //TODO
    }

    /**
     * @return array|bool
     */
    public function upload()
    {
        if ($this->validate()) {
            $path = Yii::getAlias('@uploads');
            $fileName = uniqid();
            $fileExt = $this->imageFile->extension;
            $full_name = $fileName.'.'.$fileExt;
            $this->imageFile->saveAs($path. '/' .$full_name);
            return [
                    'full_name' => $full_name,

            ];
        }
        return false;
    }

}